//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabTaskk.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CusId { get; set; }
        public string CusName { get; set; }
        public string CusAddress { get; set; }
    
        public virtual CustomersProduct CustomersProduct { get; set; }
    }
}
