//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabTaskk.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomersProduct
    {
        public int CPid { get; set; }
        public int Custold { get; set; }
        public int ProduId { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
